### ISSUE TITLE
run train_gender_classifier.py in spyder(windows10,python3),get a input data error!

### ISSUE THREAD

**Issue by CodeCat-Q** [oarriaga/face_classification#105]
**### ValueError: No data provided for "input_4". Need data for each key in: ['input_4']**

**details:**
Traceback (most recent call last):

  File "<ipython-input-4-625b305ec6bd>", line 1, in <module>
    runfile('E:/Python_Space/face_classification-master/src/train_gender_classifier.py', wdir='E:/Python_Space/face_classification-master/src')

  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/Python_Space/face_classification-master/src/train_gender_classifier.py", line 92, in <module>
    validation_steps=int(len(val_keys) / batch_size))

  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)

  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training_generator.py", line 217, in fit_generator
    class_weight=class_weight)

  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 1211, in train_on_batch
    class_weight=class_weight)

  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 751, in _standardize_user_data
    exception_prefix='input')

  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training_utils.py", line 78, in standardize_input_data
    'for each key in: ' + str(names))

ValueError: No data provided for "input_4". Need data for each key in: ['input_4']

 the exception occur in standardize_input_data() of training_utils.py:
if isinstance(data, dict):
        try:
            data = [
                data[x].values
                if data[x].__class__.__name__ == 'DataFrame' else data[x]
                for x in names
            ]
        except KeyError as e:
            raise ValueError('No data provided for "' + e.args[0] +
                             '". Need data '
                             'for each key in: ' + str(names))

**but i run it in cmd environment, it didnot get the error.**
**why??? please someone can help me!**

**Comment by VirajDeshwal** [comment]
it runs using cmd because you need to provide an argument in cmd. While in spyder you are not providing an argument and thus raising a value missing error.
