### ISSUE TITLE
error on running

### ISSUE THREAD

**Issue by Antwnina** [oarriaga/face_classification#113]
MacBook-Pro:GitHub userA$ cd face_classification/
MacBook-Pro:face_classification userA$ ls
Dockerfile		README.md		datasets		report.pdf		trained_models
LICENSE			REQUIREMENTS.txt	images			src
MacBook-Pro:face_classification userA$ ls -a
.			.gitignore		README.md		images			trained_models
..			Dockerfile		REQUIREMENTS.txt	report.pdf
.git			LICENSE			datasets		src
MacBook-Pro:face_classification userA$ cd src/
MacBook-Pro:src userA$ python3 video_emotion_color_demo.py 
Traceback (most recent call last):
  File "video_emotion_color_demo.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
MacBook-Pro:src userA$ python3 image_gradcam_demo.py
Traceback (most recent call last):
  File "image_gradcam_demo.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
MacBook-Pro:src userA$ python3 image_emotion_gender_demo.py ../images/test_image.jpg 
Traceback (most recent call last):
  File "image_emotion_gender_demo.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
MacBook-Pro:src userA$

**Comment by billyceline** [comment]
You need to install opencv library, before you run the demo
