### ISSUE TITLE
NotImplementedError when use fer2013_mini_XCEPTION.110-0.65.hdf5

### ISSUE THREAD

**Issue by Jinkeycode** [oarriaga/face_classification#28]
When I use model like...XCEPTION...hdf5,  it will raise NotImplementedError.
```
Traceback (most recent call last):
  File "/Users/Name/Documents/face_classification-master/src/image_emotion_gender_demo.py", line 35, in <module>
    gender_classifier = load_model(gender_model_path, compile=False)
  File "/Users/Name/Documents/face_classification-master/FaceDector/lib/python3.6/site-packages/keras/models.py", line 239, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/Users/Name/Documents/face_classification-master/FaceDector/lib/python3.6/site-packages/keras/models.py", line 313, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/Users/Name/Documents/face_classification-master/FaceDector/lib/python3.6/site-packages/keras/layers/__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "/Users/Name/Documents/face_classification-master/FaceDector/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
  File "/Users/Name/Documents/face_classification-master/FaceDector/lib/python3.6/site-packages/keras/engine/topology.py", line 2497, in from_config
    process_node(layer, node_data)
  File "/Users/Name/Documents/face_classification-master/FaceDector/lib/python3.6/site-packages/keras/engine/topology.py", line 2454, in process_node
    layer(input_tensors[0], **kwargs)
  File "/Users/Name/Documents/face_classification-master/FaceDector/lib/python3.6/site-packages/keras/engine/topology.py", line 602, in __call__
    output = self.call(inputs, **kwargs)
  File "/Users/Name/Documents/face_classification-master/FaceDector/lib/python3.6/site-packages/keras/layers/convolutional.py", line 1220, in call
    padding=self.padding)
  File "/Users/Name/Documents/face_classification-master/FaceDector/lib/python3.6/site-packages/keras/backend/theano_backend.py", line 1954, in separable_conv2d
    raise NotImplementedError
NotImplementedError
```

**Comment by oarriaga** [comment]
Your problem might be related to your keras version.

**Comment by RikVN** [comment]
I have the exact same error, the problem was that I used the Theano backend instead of Tensorflow. Maybe this will help someone.
