### ISSUE TITLE
ValueError: Error when checking

### ISSUE THREAD

**Issue by Nareshchary** [oarriaga/face_classification#32]
/home/hadoop/anaconda3/bin/python3.6 /home/hadoop/naresh/face_classification-master/src/video_emotion_gender_demo.py
Using TensorFlow backend.
2017-09-18 10:39:57.354480: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-18 10:39:57.354537: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
Traceback (most recent call last):
  File "/home/hadoop/naresh/face_classification-master/src/video_emotion_gender_demo.py", line 72, in <module>
    gender_prediction = gender_classifier.predict(rgb_face)
  File "/home/hadoop/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1499, in predict
    check_batch_axis=False)
  File "/home/hadoop/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 140, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking : expected input_1 to have shape (None, 64, 64, 1) but got array with shape (1, 64, 64, 3)

Process finished with exit code 1

**Comment by oarriaga** [comment]
Thank you for your interest in the code and your error message. Are you using the latest version of keras and tf? Are you using the channels at end flag in the keras config file? I just downloaded a clean version of the code and it worked for me.

**Comment by Nareshchary** [comment]
Thank you orriaga for the response.
now its working.
// can you plzz specify at what epoch earlystopping() terminated ur code and how many epochs u had given  and how much time took for the training for emotion & gender (mention ur system configuration ). Thank you

**Comment by oarriaga** [comment]
The number of epochs needed to train the classifiers are indicated in every model's name. Time depends on your current hardware.
