### ISSUE TITLE
error in train_emotion_classifier

### ISSUE THREAD

**Issue by barotdhrumil21** [oarriaga/face_classification#33]
I do have all required dependencies installed and working in other projects but when I run 'train_emotion_classifier.py' I get  following traceback::

Traceback (most recent call last):
  File "C:/Users/barot/Desktop/ml work/face_classification-master/src/train_emotion_classifier.py", line 11, in <module>
    from keras.preprocessing.image import ImageDataGenerator
  File "C:\Users\barot\AppData\Local\Programs\Python\Python35-32\lib\site-packages\keras\preprocessing\image.py", line 10, in <module>
    from scipy import linalg
  File "C:\Users\barot\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\__init__.py", line 114, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "C:\Users\barot\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\_lib\_ccallback.py", line 1, in <module>
    from . import _ccallback_c
  File "C:\Users\barot\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\_lib\_ccallback_c.py", line 7, in <module>
    __bootstrap__()
  File "C:\Users\barot\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\_lib\_ccallback_c.py", line 6, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
  File "C:\Users\barot\AppData\Local\Programs\Python\Python35\Lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

I have been trying  to understand but I can't and I am preparing a bigger project of which this is an important part and I am close to my deadline.I am student so I don't really have lot of experience so I will appreciate your help and time.Peace

**Comment by singireddysravankumar** [comment]
Please follow this link http://www.codesofinterest.com/2017/02/installing-opencv-3-python-35-windows.html . I think this can help you.
