### ISSUE TITLE
PROBLEM  in running the train gender classiffier

### ISSUE THREAD

**Issue by shahinhajiali** [oarriaga/face_classification#42]
I follow the instrument and I faces this error:

Using TensorFlow backend.
2017-11-11 13:25:44.338135: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Traceback (most recent call last):
  File "train_gender_classifier.py", line 33, in <module>
    ground_truth_data = data_loader.get_data()
  File "/home/neo/Desktop/GenderCl/face_classification-master/utils/datasets.py", line 29, in get_data
    ground_truth_data = self._load_imdb()
  File "/home/neo/Desktop/GenderCl/face_classification-master/utils/datasets.py", line 38, in _load_imdb
    dataset = loadmat(self.dataset_path)
  File "/home/neo/.virtualenvs/dl4cv/lib/python3.5/site-packages/scipy/io/matlab/mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/home/neo/.virtualenvs/dl4cv/lib/python3.5/site-packages/scipy/io/matlab/mio.py", line 64, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
TypeError: 'NoneType' object is not iterable

Please help me how can i solve this?

**Comment by mirceaciu** [comment]
Do you have any data in the `datasets` folder? It should be looking for `datasets/imdb_crop/imdb.mat`
