### ISSUE TITLE
  File "/scratch/anaconda3/envs/deep_emotion/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 701, in __del__ TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by monajalal** [oarriaga/face_classification#44]
When I ran the code for a new face, I got this error. Can you guide how to fix? I have shared the image as well.
![test_image1](https://user-images.githubusercontent.com/1892917/33052040-e04f867a-ce3a-11e7-9a44-94a6b1695809.jpg)

```
(deep_emotion) [jalal@goku src]$  python  image_emotion_gender_demo.py ../images/test_image1.jpg 
Using TensorFlow backend.
2017-11-20 21:32:30.919332: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-11-20 21:32:30.919370: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-11-20 21:32:30.919379: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-11-20 21:32:30.919394: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-11-20 21:32:30.919401: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-11-20 21:32:31.231494: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.6705
pciBusID 0000:05:00.0
Total memory: 10.91GiB
Free memory: 10.23GiB
2017-11-20 21:32:31.467503: W tensorflow/stream_executor/cuda/cuda_driver.cc:523] A non-primary context 0x2718450 exists before initializing the StreamExecutor. We haven't verified StreamExecutor works with that.
2017-11-20 21:32:31.468249: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 1 with properties: 
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.6705
pciBusID 0000:06:00.0
Total memory: 10.91GiB
Free memory: 10.75GiB
2017-11-20 21:32:31.468973: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 1 
2017-11-20 21:32:31.468991: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y Y 
2017-11-20 21:32:31.469008: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 1:   Y Y 
2017-11-20 21:32:31.469021: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:05:00.0)
2017-11-20 21:32:31.469032: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:06:00.0)
2017-11-20 21:32:32.484971: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:05:00.0)
2017-11-20 21:32:32.485010: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:06:00.0)
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7ff4db550c88>>
Traceback (most recent call last):
  File "/scratch/anaconda3/envs/deep_emotion/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 701, in __del__
TypeError: 'NoneType' object is not callable
```

**Comment by monajalal** [comment]
nvm seems it has been some transient error due to tf
![screenshot from 2017-11-20 21-45-13](https://user-images.githubusercontent.com/1892917/33052290-21c2cd32-ce3c-11e7-8402-d076a4763e74.png)
